### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_csv'

### ISSUE THREAD

**Issue by Emr-pvt** [jeremyjyang/BioClients#2]
It seems like all get function yell out an error of this type. 

I paste the logs of the error right here : 

> $ python3 -m BioClients.drugcentral.Client --o OFILE get_indication_structures
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/BioClients/drugcentral/Client.py", line 175, in <module>
    drugcentral.Utils.GetIndicationStructures(dbcon, ids, fout)
  File "/usr/local/lib/python3.8/dist-packages/BioClients/drugcentral/Utils.py", line 337, in GetIndicationStructures
    if fout: df.to_csv(fout, "\t", index=False)

**Comment by jeremyjyang** [comment]
The get_* operations all require some input ID[s], so get_indication_structures requires an OMOP ID for the indication. See https://github.com/jeremyjyang/BioClients/blob/master/doc/drugcentral.md. Use list_indications to see all. However, this operation had a bug, and treated the ID as char when it is int. Now fixed in source, so this works for Parkinson's disease:

python3 -m BioClients.drugcentral.Client get_indication_structures --ids 21001057
